---
# tasks file for ansible-role-uptime-kuma
- name: Create Storage Volume 
  ansible.builtin.file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: '0755'
    state: directory
  with_items:
    - "{{ uk_volume_directory }}"
    - "{{ uk_volume_directory }}/data"

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name:
      - ufw
    state: present
  when:
    - enable_ufw

- name: Open Firewall Port
  community.general.ufw:
    rule: allow
    port: '{{ uptime_kuma_port }}'
    proto: tcp
    src: '{{ item }}'
    comment: Allow Uptime Kuma from Private Networks
  loop: '{{ valid_sources }}'
  when:
    - enable_ufw

- name: Install Uptime Kuma Container
  community.docker.docker_container:
    name: uptime-kuma
    image: "louislam/uptime-kuma:{{ uptime_kuma_version }}"
    published_ports:
      - "{{ uptime_kuma_port }}:3001/tcp"
    env:
      NODE_EXTRA_CA_CERTS: "/app/data/CAcert.pem"
    volumes:
      - "{{ uk_volume_directory }}/data:/app/data:rw"
    restart_policy: unless-stopped
  when:
    - docker_container